# stats available at
# https://travis-ci.org/strukturag/phoenix/
language: go

sudo: false

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5

install:
  - go get github.com/dlintw/goconf
  - go get github.com/strukturag/httputils
  - go get -d -v ./... && go build -v ./...

script:
  - ./tools/check-go-fmt.sh
  - go test -v ./...
